spring.datasource.url=jdbc:postgresql://localhost:5432/reservation
spring.datasource.username=postgres
spring.datasource.password=Parikshit@12
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false